### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by elderapo** [dragomirtitian/babel-decorators-metadata#1]
This is awesome! I've been struggling to get `Reflect.getMetadata("design:type", target, key)` to work in my cra2 project for some time now... [This](https://stackoverflow.com/a/54360611/7105287) post finally explained to me why it doesn't work.

Do you have plans of publishing it as an NPM module or do you maybe want someone else to do it? I would be more than happy to do it! :)

**Comment by dragomirtitian** [comment]
I didn't have any plans to publish it, this was just the answer to an SO question originally. If you are interested in using it I will publish it, but be warned it has not really been tested beyond the sample in the repo.

**Comment by elderapo** [comment]
I would appericiate it very much! :)

**Comment by dragomirtitian** [comment]
The project is now published as `babel-plugin-decorator-metadata-typescript` and I added a readme to the project. 

Good luck, and let me know if I can help.
